<?php

namespace App\Space;

class Languages
{
    public static function getByCode($code)
    {
        return self::getLanguages()[$code];
    }

    public static function getLanguagesArray(): array
    {
        $languages = [];
        foreach (Languages::getLanguages() as $code => $language) {
            $languages[] = [
                'value' => $code,
                'title' => $language['name']
            ];
        }

        return $languages;
    }

    public static function getLanguages(): array
    {
        return [
            "af" => ["name" => "Afrikaans", "native_name" => "Afrikaans"],
            "sq" => ["name" => "Albanian - shqip", "native_name" => "shqip"],
            "am" => ["name" => "Amharic - አማርኛ", "native_name" => "አማርኛ"],
            "ar" => ["name" => "Arabic - العربية", "native_name" => "العربية"],
            "an" => ["name" => "Aragonese - aragonés", "native_name" => "aragonés"],
            "hy" => ["name" => "Armenian - հայերեն", "native_name" => "հայերեն"],
            "ast" => ["name" => "Asturian - asturianu", "native_name" => "asturianu"],
            "az" => ["name" => "Azerbaijani - azərbaycan dili", "native_name" => "azərbaycan dili"],
            "eu" => ["name" => "Basque - euskara", "native_name" => "euskara"],
            "be" => ["name" => "Belarusian - беларуская", "native_name" => "беларуская"],
            "bn" => ["name" => "Bengali - বাংলা", "native_name" => "বাংলা"],
            "bs" => ["name" => "Bosnian - bosanski", "native_name" => "bosanski"],
            "br" => ["name" => "Breton - brezhoneg", "native_name" => "brezhoneg"],
            "bg" => ["name" => "Bulgarian - български", "native_name" => "български"],
            "ca" => ["name" => "Catalan - català", "native_name" => "català"],
            "ckb" => ["name" => "Central Kurdish - کوردی (دەستنوسی عەرەبی)", "native_name" => "کوردی (دەستنوسی عەرەبی)"],
            "zh" => ["name" => "Chinese - 中文", "native_name" => "中文"],
            "zh-HK" => ["name" => "Chinese (Hong Kong) - 中文（香港）", "native_name" => "中文（香港）"],
            "zh-CN" => ["name" => "Chinese (Simplified) - 中文（简体）", "native_name" => "中文（简体）"],
            "zh-TW" => ["name" => "Chinese (Traditional) - 中文（繁體）", "native_name" => "中文（繁體）"],
            "co" => ["name" => "Corsican", "native_name" => "Corsican"],
            "hr" => ["name" => "Croatian - hrvatski", "native_name" => "hrvatski"],
            "cs" => ["name" => "Czech - čeština", "native_name" => "čeština"],
            "da" => ["name" => "Danish - dansk", "native_name" => "dansk"],
            "nl" => ["name" => "Dutch - Nederlands", "native_name" => "Nederlands"],
            "en" => ["name" => "English", "native_name" => "English"],
            "en-AU" => ["name" => "English (Australia)", "native_name" => "English (Australia)"],
            "en-CA" => ["name" => "English (Canada)", "native_name" => "English (Canada)"],
            "en-IN" => ["name" => "English (India)", "native_name" => "English (India)"],
            "en-NZ" => ["name" => "English (New Zealand)", "native_name" => "English (New Zealand)"],
            "en-ZA" => ["name" => "English (South Africa)", "native_name" => "English (South Africa)"],
            "en-GB" => ["name" => "English (United Kingdom)", "native_name" => "English (United Kingdom)"],
            "en-US" => ["name" => "English (United States)", "native_name" => "English (United States)"],
            "eo" => ["name" => "Esperanto - esperanto", "native_name" => "esperanto"],
            "et" => ["name" => "Estonian - eesti", "native_name" => "eesti"],
            "fo" => ["name" => "Faroese - føroyskt", "native_name" => "føroyskt"],
            "fil" => ["name" => "Filipino", "native_name" => "Filipino"],
            "fi" => ["name" => "Finnish - suomi", "native_name" => "suomi"],
            "fr" => ["name" => "French - français", "native_name" => "français"],
            "fr-CA" => ["name" => "French (Canada) - français (Canada)", "native_name" => "français (Canada)"],
            "fr-FR" => ["name" => "French (France) - français (France)", "native_name" => "français (France)"],
            "fr-CH" => ["name" => "French (Switzerland) - français (Suisse)", "native_name" => "français (Suisse)"],
            "gl" => ["name" => "Galician - galego", "native_name" => "galego"],
            "ka" => ["name" => "Georgian - ქართული", "native_name" => "ქართული"],
            "de" => ["name" => "German - Deutsch", "native_name" => "Deutsch"],
            "de-AT" => ["name" => "German (Austria) - Deutsch (Österreich)", "native_name" => "Deutsch (Österreich)"],
            "de-DE" => ["name" => "German (Germany) - Deutsch (Deutschland)", "native_name" => "Deutsch (Deutschland)"],
            "de-LI" => ["name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "native_name" => "Deutsch (Liechtenstein)"],
            "de-CH" => ["name" => "German (Switzerland) - Deutsch (Schweiz)", "native_name" => "Deutsch (Schweiz)"],
            "el" => ["name" => "Greek - Ελληνικά", "native_name" => "Ελληνικά"],
            "gn" => ["name" => "Guarani", "native_name" => "Guarani"],
            "gu" => ["name" => "Gujarati - ગુજરાતી", "native_name" => "ગુજરાતી"],
            "ha" => ["name" => "Hausa", "native_name" => "Hausa"],
            "haw" => ["name" => "Hawaiian - ʻŌlelo Hawaiʻi", "native_name" => "ʻŌlelo Hawaiʻi"],
            "he" => ["name" => "Hebrew - עברית", "native_name" => "עברית"],
            "hi" => ["name" => "Hindi - हिन्दी", "native_name" => "हिन्दी"],
            "hu" => ["name" => "Hungarian - magyar", "native_name" => "magyar"],
            "is" => ["name" => "Icelandic - íslenska", "native_name" => "íslenska"],
            "id" => ["name" => "Indonesian - Indonesia", "native_name" => "Indonesia"],
            "ia" => ["name" => "Interlingua", "native_name" => "Interlingua"],
            "ga" => ["name" => "Irish - Gaeilge", "native_name" => "Gaeilge"],
            "it" => ["name" => "Italian - italiano", "native_name" => "italiano"],
            "it-IT" => ["name" => "Italian (Italy) - italiano (Italia)", "native_name" => "italiano (Italia)"],
            "it-CH" => ["name" => "Italian (Switzerland) - italiano (Svizzera)", "native_name" => "italiano (Svizzera)"],
            "ja" => ["name" => "Japanese - 日本語", "native_name" => "日本語"],
            "kn" => ["name" => "Kannada - ಕನ್ನಡ", "native_name" => "ಕನ್ನಡ"],
            "kk" => ["name" => "Kazakh - қазақ тілі", "native_name" => "қазақ тілі"],
            "km" => ["name" => "Khmer - ខ្មែរ", "native_name" => "ខ្មែរ"],
            "ko" => ["name" => "Korean - 한국어", "native_name" => "한국어"],
            "ku" => ["name" => "Kurdish - Kurdî", "native_name" => "Kurdî"],
            "ky" => ["name" => "Kyrgyz - кыргызча", "native_name" => "кыргызча"],
            "lo" => ["name" => "Lao - ລາວ", "native_name" => "ລາວ"],
            "la" => ["name" => "Latin", "native_name" => "Latin"],
            "lv" => ["name" => "Latvian - latviešu", "native_name" => "latviešu"],
            "ln" => ["name" => "Lingala - lingála", "native_name" => "lingála"],
            "lt" => ["name" => "Lithuanian - lietuvių", "native_name" => "lietuvių"],
            "mk" => ["name" => "Macedonian - македонски", "native_name" => "македонски"],
            "ms" => ["name" => "Malay - Bahasa Melayu", "native_name" => "Bahasa Melayu"],
            "ml" => ["name" => "Malayalam - മലയാളം", "native_name" => "മലയാളം"],
            "mt" => ["name" => "Maltese - Malti", "native_name" => "Malti"],
            "mr" => ["name" => "Marathi - मराठी", "native_name" => "मराठी"],
            "mn" => ["name" => "Mongolian - монгол", "native_name" => "монгол"],
            "ne" => ["name" => "Nepali - नेपाली", "native_name" => "नेपाली"],
            "no" => ["name" => "Norwegian - norsk", "native_name" => "norsk"],
            "nb" => ["name" => "Norwegian Bokmål - norsk bokmål", "native_name" => "norsk bokmål"],
            "nn" => ["name" => "Norwegian Nynorsk - nynorsk", "native_name" => "nynorsk"],
            "oc" => ["name" => "Occitan", "native_name" => "Occitan"],
            "or" => ["name" => "Oriya - ଓଡ଼ିଆ", "native_name" => "ଓଡ଼ିଆ"],
            "om" => ["name" => "Oromo - Oromoo", "native_name" => "Oromoo"],
            "ps" => ["name" => "Pashto - پښتو", "native_name" => "پښتو"],
            "fa" => ["name" => "Persian - فارسی", "native_name" => "فارسی"],
            "pl" => ["name" => "Polish - polski", "native_name" => "polski"],
            "pt" => ["name" => "Portuguese - português", "native_name" => "português"],
            "pt-BR" => ["name" => "Portuguese (Brazil) - português (Brasil)", "native_name" => "português (Brasil)"],
            "pt-PT" => ["name" => "Portuguese (Portugal) - português (Portugal)", "native_name" => "português (Portugal)"],
            "pa" => ["name" => "Punjabi - ਪੰਜਾਬੀ", "native_name" => "ਪੰਜਾਬੀ"],
            "qu" => ["name" => "Quechua", "native_name" => "Quechua"],
            "ro" => ["name" => "Romanian - română", "native_name" => "română"],
            "mo" => ["name" => "Romanian (Moldova) - română (Moldova)", "native_name" => "română (Moldova)"],
            "rm" => ["name" => "Romansh - rumantsch", "native_name" => "rumantsch"],
            "ru" => ["name" => "Russian - русский", "native_name" => "русский"],
            "gd" => ["name" => "Scottish Gaelic", "native_name" => "Scottish Gaelic"],
            "sr" => ["name" => "Serbian - српски", "native_name" => "српски"],
            "sh" => ["name" => "Serbo - Croatian", "native_name" => "Croatian"],
            "sn" => ["name" => "Shona - chiShona", "native_name" => "chiShona"],
            "sd" => ["name" => "Sindhi", "native_name" => "Sindhi"],
            "si" => ["name" => "Sinhala - සිංහල", "native_name" => "සිංහල"],
            "sk" => ["name" => "Slovak - slovenčina", "native_name" => "slovenčina"],
            "sl" => ["name" => "Slovenian - slovenščina", "native_name" => "slovenščina"],
            "so" => ["name" => "Somali - Soomaali", "native_name" => "Soomaali"],
            "st" => ["name" => "Southern Sotho", "native_name" => "Southern Sotho"],
            "es" => ["name" => "Spanish - español", "native_name" => "español"],
            "es-AR" => ["name" => "Spanish (Argentina) - español (Argentina)", "native_name" => "español (Argentina)"],
            "es-419" => ["name" => "Spanish (Latin America) - español (Latinoamérica)", "native_name" => "español (Latinoamérica)"],
            "es-MX" => ["name" => "Spanish (Mexico) - español (México)", "native_name" => "español (México)"],
            "es-ES" => ["name" => "Spanish (Spain) - español (España)", "native_name" => "español (España)"],
            "es-US" => ["name" => "Spanish (United States) - español (Estados Unidos)", "native_name" => "español (Estados Unidos)"],
            "su" => ["name" => "Sundanese", "native_name" => "Sundanese"],
            "sw" => ["name" => "Swahili - Kiswahili", "native_name" => "Kiswahili"],
            "sv" => ["name" => "Swedish - svenska", "native_name" => "svenska"],
            "tg" => ["name" => "Tajik - тоҷикӣ", "native_name" => "тоҷикӣ"],
            "ta" => ["name" => "Tamil - தமிழ்", "native_name" => "தமிழ்"],
            "tt" => ["name" => "Tatar", "native_name" => "Tatar"],
            "te" => ["name" => "Telugu - తెలుగు", "native_name" => "తెలుగు"],
            "th" => ["name" => "Thai - ไทย", "native_name" => "ไทย"],
            "ti" => ["name" => "Tigrinya - ትግርኛ", "native_name" => "ትግርኛ"],
            "to" => ["name" => "Tongan - lea fakatonga", "native_name" => "lea fakatonga"],
            "tr" => ["name" => "Turkish - Türkçe", "native_name" => "Türkçe"],
            "tk" => ["name" => "Turkmen", "native_name" => "Turkmen"],
            "tw" => ["name" => "Twi", "native_name" => "Twi"],
            "uk" => ["name" => "Ukrainian - українська", "native_name" => "українська"],
            "ur" => ["name" => "Urdu - اردو", "native_name" => "اردو"],
            "ug" => ["name" => "Uyghur", "native_name" => "Uyghur"],
            "uz" => ["name" => "Uzbek - o‘zbek", "native_name" => "o‘zbek"],
            "vi" => ["name" => "Vietnamese - Tiếng Việt", "native_name" => "Tiếng Việt"],
            "wa" => ["name" => "Walloon - wa", "native_name" => "wa"],
            "cy" => ["name" => "Welsh - Cymraeg", "native_name" => "Cymraeg"],
            "fy" => ["name" => "Western Frisian", "native_name" => "Western Frisian"],
            "xh" => ["name" => "Xhosa", "native_name" => "Xhosa"],
            "yi" => ["name" => "Yiddish", "native_name" => "Yiddish"],
            "yo" => ["name" => "Yoruba - Èdè Yorùbá", "native_name" => "Èdè Yorùbá"],
            "zu" => ["name" => "Zulu - isiZulu", "native_name" => "isiZulu"]
        ];

    }
}
