<?php

namespace App\Space;

class TimeZone
{
    public static function get_list()
    {
        return [
            ['value' => 'Pacific/Midway', 'title' => '(UTC-11:00) Midway'],
            ['value' => 'Pacific/Niue', 'title' => '(UTC-11:00) Niue'],
            ['value' => 'Pacific/Pago_Pago', 'title' => '(UTC-11:00) Pago Pago'],
            ['value' => 'America/Adak', 'title' => '(UTC-10:00) Adak'],
            ['value' => 'Pacific/Honolulu', 'title' => '(UTC-10:00) Honolulu'],
            ['value' => 'Pacific/Johnston', 'title' => '(UTC-10:00) Johnston'],
            ['value' => 'Pacific/Rarotonga', 'title' => '(UTC-10:00) Rarotonga'],
            ['value' => 'Pacific/Tahiti', 'title' => '(UTC-10:00) Tahiti'],
            ['value' => 'Pacific/Marquesas', 'title' => '(UTC-09:30) Marquesas'],
            ['value' => 'America/Anchorage', 'title' => '(UTC-09:00) Anchorage'],
            ['value' => 'Pacific/Gambier', 'title' => '(UTC-09:00) Gambier'],
            ['value' => 'America/Juneau', 'title' => '(UTC-09:00) Juneau'],
            ['value' => 'America/Nome', 'title' => '(UTC-09:00) Nome'],
            ['value' => 'America/Sitka', 'title' => '(UTC-09:00) Sitka'],
            ['value' => 'America/Yakutat', 'title' => '(UTC-09:00) Yakutat'],
            ['value' => 'America/Dawson', 'title' => '(UTC-08:00) Dawson'],
            ['value' => 'America/Los_Angeles', 'title' => '(UTC-08:00) Los Angeles'],
            ['value' => 'America/Metlakatla', 'title' => '(UTC-08:00) Metlakatla'],
            ['value' => 'Pacific/Pitcairn', 'title' => '(UTC-08:00) Pitcairn'],
            ['value' => 'America/Santa_Isabel', 'title' => '(UTC-08:00) Santa Isabel'],
            ['value' => 'America/Tijuana', 'title' => '(UTC-08:00) Tijuana'],
            ['value' => 'America/Vancouver', 'title' => '(UTC-08:00) Vancouver'],
            ['value' => 'America/Whitehorse', 'title' => '(UTC-08:00) Whitehorse'],
            ['value' => 'America/Boise', 'title' => '(UTC-07:00) Boise'],
            ['value' => 'America/Cambridge_Bay', 'title' => '(UTC-07:00) Cambridge Bay'],
            ['value' => 'America/Chihuahua', 'title' => '(UTC-07:00) Chihuahua'],
            ['value' => 'America/Creston', 'title' => '(UTC-07:00) Creston'],
            ['value' => 'America/Dawson_Creek', 'title' => '(UTC-07:00) Dawson Creek'],
            ['value' => 'America/Denver', 'title' => '(UTC-07:00) Denver'],
            ['value' => 'America/Edmonton', 'title' => '(UTC-07:00) Edmonton'],
            ['value' => 'America/Hermosillo', 'title' => '(UTC-07:00) Hermosillo'],
            ['value' => 'America/Inuvik', 'title' => '(UTC-07:00) Inuvik'],
            ['value' => 'America/Mazatlan', 'title' => '(UTC-07:00) Mazatlan'],
            ['value' => 'America/Ojinaga', 'title' => '(UTC-07:00) Ojinaga'],
            ['value' => 'America/Phoenix', 'title' => '(UTC-07:00) Phoenix'],
            ['value' => 'America/Shiprock', 'title' => '(UTC-07:00) Shiprock'],
            ['value' => 'America/Yellowknife', 'title' => '(UTC-07:00) Yellowknife'],
            ['value' => 'America/Bahia_Banderas', 'title' => '(UTC-06:00) Bahia Banderas'],
            ['value' => 'America/Belize', 'title' => '(UTC-06:00) Belize'],
            ['value' => 'America/North_Dakota/Beulah', 'title' => '(UTC-06:00) Beulah'],
            ['value' => 'America/Cancun', 'title' => '(UTC-06:00) Cancun'],
            ['value' => 'America/North_Dakota/Center', 'title' => '(UTC-06:00) Center'],
            ['value' => 'America/Chicago', 'title' => '(UTC-06:00) Chicago'],
            ['value' => 'America/Costa_Rica', 'title' => '(UTC-06:00) Costa Rica'],
            ['value' => 'Pacific/Easter', 'title' => '(UTC-06:00) Easter'],
            ['value' => 'America/El_Salvador', 'title' => '(UTC-06:00) El Salvador'],
            ['value' => 'Pacific/Galapagos', 'title' => '(UTC-06:00) Galapagos'],
            ['value' => 'America/Guatemala', 'title' => '(UTC-06:00) Guatemala'],
            ['value' => 'America/Indiana/Knox', 'title' => '(UTC-06:00) Knox'],
            ['value' => 'America/Managua', 'title' => '(UTC-06:00) Managua'],
            ['value' => 'America/Matamoros', 'title' => '(UTC-06:00) Matamoros'],
            ['value' => 'America/Menominee', 'title' => '(UTC-06:00) Menominee'],
            ['value' => 'America/Merida', 'title' => '(UTC-06:00) Merida'],
            ['value' => 'America/Mexico_City', 'title' => '(UTC-06:00) Mexico City'],
            ['value' => 'America/Monterrey', 'title' => '(UTC-06:00) Monterrey'],
            ['value' => 'America/North_Dakota/New_Salem', 'title' => '(UTC-06:00) New Salem'],
            ['value' => 'America/Rainy_River', 'title' => '(UTC-06:00) Rainy River'],
            ['value' => 'America/Rankin_Inlet', 'title' => '(UTC-06:00) Rankin Inlet'],
            ['value' => 'America/Regina', 'title' => '(UTC-06:00) Regina'],
            ['value' => 'America/Resolute', 'title' => '(UTC-06:00) Resolute'],
            ['value' => 'America/Swift_Current', 'title' => '(UTC-06:00) Swift Current'],
            ['value' => 'America/Tegucigalpa', 'title' => '(UTC-06:00) Tegucigalpa'],
            ['value' => 'America/Indiana/Tell_City', 'title' => '(UTC-06:00) Tell City'],
            ['value' => 'America/Winnipeg', 'title' => '(UTC-06:00) Winnipeg'],
            ['value' => 'America/Atikokan', 'title' => '(UTC-05:00) Atikokan'],
            ['value' => 'America/Bogota', 'title' => '(UTC-05:00) Bogota'],
            ['value' => 'America/Cayman', 'title' => '(UTC-05:00) Cayman'],
            ['value' => 'America/Detroit', 'title' => '(UTC-05:00) Detroit'],
            ['value' => 'America/Grand_Turk', 'title' => '(UTC-05:00) Grand Turk'],
            ['value' => 'America/Guayaquil', 'title' => '(UTC-05:00) Guayaquil'],
            ['value' => 'America/Havana', 'title' => '(UTC-05:00) Havana'],
            ['value' => 'America/Indiana/Indianapolis', 'title' => '(UTC-05:00) Indianapolis'],
            ['value' => 'America/Iqaluit', 'title' => '(UTC-05:00) Iqaluit'],
            ['value' => 'America/Jamaica', 'title' => '(UTC-05:00) Jamaica'],
            ['value' => 'America/Lima', 'title' => '(UTC-05:00) Lima'],
            ['value' => 'America/Kentucky/Louisville', 'title' => '(UTC-05:00) Louisville'],
            ['value' => 'America/Indiana/Marengo', 'title' => '(UTC-05:00) Marengo'],
            ['value' => 'America/Kentucky/Monticello', 'title' => '(UTC-05:00) Monticello'],
            ['value' => 'America/Montreal', 'title' => '(UTC-05:00) Montreal'],
            ['value' => 'America/Nassau', 'title' => '(UTC-05:00) Nassau'],
            ['value' => 'America/New_York', 'title' => '(UTC-05:00) New York'],
            ['value' => 'America/Nipigon', 'title' => '(UTC-05:00) Nipigon'],
            ['value' => 'America/Panama', 'title' => '(UTC-05:00) Panama'],
            ['value' => 'America/Pangnirtung', 'title' => '(UTC-05:00) Pangnirtung'],
            ['value' => 'America/Indiana/Petersburg', 'title' => '(UTC-05:00) Petersburg'],
            ['value' => 'America/Port-au-Prince', 'title' => '(UTC-05:00) Port-au-Prince'],
            ['value' => 'America/Thunder_Bay', 'title' => '(UTC-05:00) Thunder Bay'],
            ['value' => 'America/Toronto', 'title' => '(UTC-05:00) Toronto'],
            ['value' => 'America/Indiana/Vevay', 'title' => '(UTC-05:00) Vevay'],
            ['value' => 'America/Indiana/Vincennes', 'title' => '(UTC-05:00) Vincennes'],
            ['value' => 'America/Indiana/Winamac', 'title' => '(UTC-05:00) Winamac'],
            ['value' => 'America/Caracas', 'title' => '(UTC-04:30) Caracas'],
            ['value' => 'America/Anguilla', 'title' => '(UTC-04:00) Anguilla'],
            ['value' => 'America/Antigua', 'title' => '(UTC-04:00) Antigua'],
            ['value' => 'America/Aruba', 'title' => '(UTC-04:00) Aruba'],
            ['value' => 'America/Asuncion', 'title' => '(UTC-04:00) Asuncion'],
            ['value' => 'America/Barbados', 'title' => '(UTC-04:00) Barbados'],
            ['value' => 'Atlantic/Bermuda', 'title' => '(UTC-04:00) Bermuda'],
            ['value' => 'America/Blanc-Sablon', 'title' => '(UTC-04:00) Blanc-Sablon'],
            ['value' => 'America/Boa_Vista', 'title' => '(UTC-04:00) Boa Vista'],
            ['value' => 'America/Campo_Grande', 'title' => '(UTC-04:00) Campo Grande'],
            ['value' => 'America/Cuiaba', 'title' => '(UTC-04:00) Cuiaba'],
            ['value' => 'America/Curacao', 'title' => '(UTC-04:00) Curacao'],
            ['value' => 'America/Dominica', 'title' => '(UTC-04:00) Dominica'],
            ['value' => 'America/Eirunepe', 'title' => '(UTC-04:00) Eirunepe'],
            ['value' => 'America/Glace_Bay', 'title' => '(UTC-04:00) Glace Bay'],
            ['value' => 'America/Goose_Bay', 'title' => '(UTC-04:00) Goose Bay'],
            ['value' => 'America/Grenada', 'title' => '(UTC-04:00) Grenada'],
            ['value' => 'America/Guadeloupe', 'title' => '(UTC-04:00) Guadeloupe'],
            ['value' => 'America/Guyana', 'title' => '(UTC-04:00) Guyana'],
            ['value' => 'America/Halifax', 'title' => '(UTC-04:00) Halifax'],
            ['value' => 'America/Kralendijk', 'title' => '(UTC-04:00) Kralendijk'],
            ['value' => 'America/La_Paz', 'title' => '(UTC-04:00) La Paz'],
            ['value' => 'America/Lower_Princes', 'title' => '(UTC-04:00) Lower Princes'],
            ['value' => 'America/Manaus', 'title' => '(UTC-04:00) Manaus'],
            ['value' => 'America/Marigot', 'title' => '(UTC-04:00) Marigot'],
            ['value' => 'America/Martinique', 'title' => '(UTC-04:00) Martinique'],
            ['value' => 'America/Moncton', 'title' => '(UTC-04:00) Moncton'],
            ['value' => 'America/Montserrat', 'title' => '(UTC-04:00) Montserrat'],
            ['value' => 'Antarctica/Palmer', 'title' => '(UTC-04:00) Palmer'],
            ['value' => 'America/Port_of_Spain', 'title' => '(UTC-04:00) Port of Spain'],
            ['value' => 'America/Porto_Velho', 'title' => '(UTC-04:00) Porto Velho'],
            ['value' => 'America/Puerto_Rico', 'title' => '(UTC-04:00) Puerto Rico'],
            ['value' => 'America/Rio_Branco', 'title' => '(UTC-04:00) Rio Branco'],
            ['value' => 'America/Santiago', 'title' => '(UTC-04:00) Santiago'],
            ['value' => 'America/Santo_Domingo', 'title' => '(UTC-04:00) Santo Domingo'],
            ['value' => 'America/St_Barthelemy', 'title' => '(UTC-04:00) St. Barthelemy'],
            ['value' => 'America/St_Kitts', 'title' => '(UTC-04:00) St. Kitts'],
            ['value' => 'America/St_Lucia', 'title' => '(UTC-04:00) St. Lucia'],
            ['value' => 'America/St_Thomas', 'title' => '(UTC-04:00) St. Thomas'],
            ['value' => 'America/St_Vincent', 'title' => '(UTC-04:00) St. Vincent'],
            ['value' => 'America/Thule', 'title' => '(UTC-04:00) Thule'],
            ['value' => 'America/Tortola', 'title' => '(UTC-04:00) Tortola'],
            ['value' => 'America/St_Johns', 'title' => '(UTC-03:30) St. Johns'],
            ['value' => 'America/Araguaina', 'title' => '(UTC-03:00) Araguaina'],
            ['value' => 'America/Bahia', 'title' => '(UTC-03:00) Bahia'],
            ['value' => 'America/Belem', 'title' => '(UTC-03:00) Belem'],
            ['value' => 'America/Argentina/Buenos_Aires', 'title' => '(UTC-03:00) Buenos Aires'],
            ['value' => 'America/Argentina/Catamarca', 'title' => '(UTC-03:00) Catamarca'],
            ['value' => 'America/Cayenne', 'title' => '(UTC-03:00) Cayenne'],
            ['value' => 'America/Argentina/Cordoba', 'title' => '(UTC-03:00) Cordoba'],
            ['value' => 'America/Fortaleza', 'title' => '(UTC-03:00) Fortaleza'],
            ['value' => 'America/Godthab', 'title' => '(UTC-03:00) Godthab'],
            ['value' => 'America/Argentina/Jujuy', 'title' => '(UTC-03:00) Jujuy'],
            ['value' => 'America/Argentina/La_Rioja', 'title' => '(UTC-03:00) La Rioja'],
            ['value' => 'America/Maceio', 'title' => '(UTC-03:00) Maceio'],
            ['value' => 'America/Argentina/Mendoza', 'title' => '(UTC-03:00) Mendoza'],
            ['value' => 'America/Miquelon', 'title' => '(UTC-03:00) Miquelon'],
            ['value' => 'America/Montevideo', 'title' => '(UTC-03:00) Montevideo'],
            ['value' => 'America/Paramaribo', 'title' => '(UTC-03:00) Paramaribo'],
            ['value' => 'America/Recife', 'title' => '(UTC-03:00) Recife'],
            ['value' => 'America/Argentina/Rio_Gallegos', 'title' => '(UTC-03:00) Rio Gallegos'],
            ['value' => 'Antarctica/Rothera', 'title' => '(UTC-03:00) Rothera'],
            ['value' => 'America/Argentina/Salta', 'title' => '(UTC-03:00) Salta'],
            ['value' => 'America/Argentina/San_Juan', 'title' => '(UTC-03:00) San Juan'],
            ['value' => 'America/Argentina/San_Luis', 'title' => '(UTC-03:00) San Luis'],
            ['value' => 'America/Santarem', 'title' => '(UTC-03:00) Santarem'],
            ['value' => 'America/Sao_Paulo', 'title' => '(UTC-03:00) Sao Paulo'],
            ['value' => 'Atlantic/Stanley', 'title' => '(UTC-03:00) Stanley'],
            ['value' => 'America/Argentina/Tucuman', 'title' => '(UTC-03:00) Tucuman'],
            ['value' => 'America/Argentina/Ushuaia', 'title' => '(UTC-03:00) Ushuaia'],
            ['value' => 'America/Noronha', 'title' => '(UTC-02:00) Noronha'],
            ['value' => 'Atlantic/South_Georgia', 'title' => '(UTC-02:00) South Georgia'],
            ['value' => 'Atlantic/Azores', 'title' => '(UTC-01:00) Azores'],
            ['value' => 'Atlantic/Cape_Verde', 'title' => '(UTC-01:00) Cape Verde'],
            ['value' => 'America/Scoresbysund', 'title' => '(UTC-01:00) Scoresbysund'],
            ['value' => 'Africa/Abidjan', 'title' => '(UTC+00:00) Abidjan'],
            ['value' => 'Africa/Accra', 'title' => '(UTC+00:00) Accra'],
            ['value' => 'Africa/Bamako', 'title' => '(UTC+00:00) Bamako'],
            ['value' => 'Africa/Banjul', 'title' => '(UTC+00:00) Banjul'],
            ['value' => 'Africa/Bissau', 'title' => '(UTC+00:00) Bissau'],
            ['value' => 'Atlantic/Canary', 'title' => '(UTC+00:00) Canary'],
            ['value' => 'Africa/Casablanca', 'title' => '(UTC+00:00) Casablanca'],
            ['value' => 'Africa/Conakry', 'title' => '(UTC+00:00) Conakry'],
            ['value' => 'Africa/Dakar', 'title' => '(UTC+00:00) Dakar'],
            ['value' => 'America/Danmarkshavn', 'title' => '(UTC+00:00) Danmarkshavn'],
            ['value' => 'Europe/Dublin', 'title' => '(UTC+00:00) Dublin'],
            ['value' => 'Africa/El_Aaiun', 'title' => '(UTC+00:00) El Aaiun'],
            ['value' => 'Atlantic/Faroe', 'title' => '(UTC+00:00) Faroe'],
            ['value' => 'Africa/Freetown', 'title' => '(UTC+00:00) Freetown'],
            ['value' => 'Europe/Guernsey', 'title' => '(UTC+00:00) Guernsey'],
            ['value' => 'Europe/Isle_of_Man', 'title' => '(UTC+00:00) Isle of Man'],
            ['value' => 'Europe/Jersey', 'title' => '(UTC+00:00) Jersey'],
            ['value' => 'Europe/Lisbon', 'title' => '(UTC+00:00) Lisbon'],
            ['value' => 'Africa/Lome', 'title' => '(UTC+00:00) Lome'],
            ['value' => 'Europe/London', 'title' => '(UTC+00:00) London'],
            ['value' => 'Atlantic/Madeira', 'title' => '(UTC+00:00) Madeira'],
            ['value' => 'Africa/Monrovia', 'title' => '(UTC+00:00) Monrovia'],
            ['value' => 'Africa/Nouakchott', 'title' => '(UTC+00:00) Nouakchott'],
            ['value' => 'Africa/Ouagadougou', 'title' => '(UTC+00:00) Ouagadougou'],
            ['value' => 'Atlantic/Reykjavik', 'title' => '(UTC+00:00) Reykjavik'],
            ['value' => 'Africa/Sao_Tome', 'title' => '(UTC+00:00) Sao Tome'],
            ['value' => 'Atlantic/St_Helena', 'title' => '(UTC+00:00) St. Helena'],
            ['value' => 'UTC', 'title' => '(UTC+00:00) UTC'],
            ['value' => 'Africa/Algiers', 'title' => '(UTC+01:00) Algiers'],
            ['value' => 'Europe/Amsterdam', 'title' => '(UTC+01:00) Amsterdam'],
            ['value' => 'Europe/Andorra', 'title' => '(UTC+01:00) Andorra'],
            ['value' => 'Africa/Bangui', 'title' => '(UTC+01:00) Bangui'],
            ['value' => 'Europe/Belgrade', 'title' => '(UTC+01:00) Belgrade'],
            ['value' => 'Europe/Berlin', 'title' => '(UTC+01:00) Berlin'],
            ['value' => 'Europe/Bratislava', 'title' => '(UTC+01:00) Bratislava'],
            ['value' => 'Africa/Brazzaville', 'title' => '(UTC+01:00) Brazzaville'],
            ['value' => 'Europe/Brussels', 'title' => '(UTC+01:00) Brussels'],
            ['value' => 'Europe/Budapest', 'title' => '(UTC+01:00) Budapest'],
            ['value' => 'Europe/Busingen', 'title' => '(UTC+01:00) Busingen'],
            ['value' => 'Africa/Ceuta', 'title' => '(UTC+01:00) Ceuta'],
            ['value' => 'Europe/Copenhagen', 'title' => '(UTC+01:00) Copenhagen'],
            ['value' => 'Africa/Douala', 'title' => '(UTC+01:00) Douala'],
            ['value' => 'Europe/Gibraltar', 'title' => '(UTC+01:00) Gibraltar'],
            ['value' => 'Africa/Kinshasa', 'title' => '(UTC+01:00) Kinshasa'],
            ['value' => 'Africa/Lagos', 'title' => '(UTC+01:00) Lagos'],
            ['value' => 'Africa/Libreville', 'title' => '(UTC+01:00) Libreville'],
            ['value' => 'Europe/Ljubljana', 'title' => '(UTC+01:00) Ljubljana'],
            ['value' => 'Arctic/Longyearbyen', 'title' => '(UTC+01:00) Longyearbyen'],
            ['value' => 'Africa/Luanda', 'title' => '(UTC+01:00) Luanda'],
            ['value' => 'Europe/Luxembourg', 'title' => '(UTC+01:00) Luxembourg'],
            ['value' => 'Europe/Madrid', 'title' => '(UTC+01:00) Madrid'],
            ['value' => 'Africa/Malabo', 'title' => '(UTC+01:00) Malabo'],
            ['value' => 'Europe/Malta', 'title' => '(UTC+01:00) Malta'],
            ['value' => 'Europe/Monaco', 'title' => '(UTC+01:00) Monaco'],
            ['value' => 'Africa/Ndjamena', 'title' => '(UTC+01:00) Ndjamena'],
            ['value' => 'Africa/Niamey', 'title' => '(UTC+01:00) Niamey'],
            ['value' => 'Europe/Oslo', 'title' => '(UTC+01:00) Oslo'],
            ['value' => 'Europe/Paris', 'title' => '(UTC+01:00) Paris'],
            ['value' => 'Europe/Podgorica', 'title' => '(UTC+01:00) Podgorica'],
            ['value' => 'Africa/Porto-Novo', 'title' => '(UTC+01:00) Porto-Novo'],
            ['value' => 'Europe/Prague', 'title' => '(UTC+01:00) Prague'],
            ['value' => 'Europe/Rome', 'title' => '(UTC+01:00) Rome'],
            ['value' => 'Europe/San_Marino', 'title' => '(UTC+01:00) San Marino'],
            ['value' => 'Europe/Sarajevo', 'title' => '(UTC+01:00) Sarajevo'],
            ['value' => 'Europe/Skopje', 'title' => '(UTC+01:00) Skopje'],
            ['value' => 'Europe/Stockholm', 'title' => '(UTC+01:00) Stockholm'],
            ['value' => 'Europe/Tirane', 'title' => '(UTC+01:00) Tirane'],
            ['value' => 'Africa/Tripoli', 'title' => '(UTC+01:00) Tripoli'],
            ['value' => 'Africa/Tunis', 'title' => '(UTC+01:00) Tunis'],
            ['value' => 'Europe/Vaduz', 'title' => '(UTC+01:00) Vaduz'],
            ['value' => 'Europe/Vatican', 'title' => '(UTC+01:00) Vatican'],
            ['value' => 'Europe/Vienna', 'title' => '(UTC+01:00) Vienna'],
            ['value' => 'Europe/Warsaw', 'title' => '(UTC+01:00) Warsaw'],
            ['value' => 'Africa/Windhoek', 'title' => '(UTC+01:00) Windhoek'],
            ['value' => 'Europe/Zagreb', 'title' => '(UTC+01:00) Zagreb'],
            ['value' => 'Europe/Zurich', 'title' => '(UTC+01:00) Zurich'],
            ['value' => 'Europe/Athens', 'title' => '(UTC+02:00) Athens'],
            ['value' => 'Asia/Beirut', 'title' => '(UTC+02:00) Beirut'],
            ['value' => 'Africa/Blantyre', 'title' => '(UTC+02:00) Blantyre'],
            ['value' => 'Europe/Bucharest', 'title' => '(UTC+02:00) Bucharest'],
            ['value' => 'Africa/Bujumbura', 'title' => '(UTC+02:00) Bujumbura'],
            ['value' => 'Africa/Cairo', 'title' => '(UTC+02:00) Cairo'],
            ['value' => 'Europe/Chisinau', 'title' => '(UTC+02:00) Chisinau'],
            ['value' => 'Asia/Damascus', 'title' => '(UTC+02:00) Damascus'],
            ['value' => 'Africa/Gaborone', 'title' => '(UTC+02:00) Gaborone'],
            ['value' => 'Asia/Gaza', 'title' => '(UTC+02:00) Gaza'],
            ['value' => 'Africa/Harare', 'title' => '(UTC+02:00) Harare'],
            ['value' => 'Asia/Hebron', 'title' => '(UTC+02:00) Hebron'],
            ['value' => 'Europe/Helsinki', 'title' => '(UTC+02:00) Helsinki'],
            ['value' => 'Europe/Istanbul', 'title' => '(UTC+02:00) Istanbul'],
            ['value' => 'Asia/Jerusalem', 'title' => '(UTC+02:00) Jerusalem'],
            ['value' => 'Africa/Johannesburg', 'title' => '(UTC+02:00) Johannesburg'],
            ['value' => 'Europe/Kiev', 'title' => '(UTC+02:00) Kiev'],
            ['value' => 'Africa/Kigali', 'title' => '(UTC+02:00) Kigali'],
            ['value' => 'Africa/Lubumbashi', 'title' => '(UTC+02:00) Lubumbashi'],
            ['value' => 'Africa/Lusaka', 'title' => '(UTC+02:00) Lusaka'],
            ['value' => 'Africa/Maputo', 'title' => '(UTC+02:00) Maputo'],
            ['value' => 'Europe/Mariehamn', 'title' => '(UTC+02:00) Mariehamn'],
            ['value' => 'Africa/Maseru', 'title' => '(UTC+02:00) Maseru'],
            ['value' => 'Africa/Mbabane', 'title' => '(UTC+02:00) Mbabane'],
            ['value' => 'Asia/Nicosia', 'title' => '(UTC+02:00) Nicosia'],
            ['value' => 'Europe/Riga', 'title' => '(UTC+02:00) Riga'],
            ['value' => 'Europe/Simferopol', 'title' => '(UTC+02:00) Simferopol'],
            ['value' => 'Europe/Sofia', 'title' => '(UTC+02:00) Sofia'],
            ['value' => 'Europe/Tallinn', 'title' => '(UTC+02:00) Tallinn'],
            ['value' => 'Europe/Uzhgorod', 'title' => '(UTC+02:00) Uzhgorod'],
            ['value' => 'Europe/Vilnius', 'title' => '(UTC+02:00) Vilnius'],
            ['value' => 'Europe/Zaporozhye', 'title' => '(UTC+02:00) Zaporozhye'],
            ['value' => 'Africa/Addis_Ababa', 'title' => '(UTC+03:00) Addis Ababa'],
            ['value' => 'Asia/Aden', 'title' => '(UTC+03:00) Aden'],
            ['value' => 'Asia/Amman', 'title' => '(UTC+03:00) Amman'],
            ['value' => 'Indian/Antananarivo', 'title' => '(UTC+03:00) Antananarivo'],
            ['value' => 'Africa/Asmara', 'title' => '(UTC+03:00) Asmara'],
            ['value' => 'Asia/Baghdad', 'title' => '(UTC+03:00) Baghdad'],
            ['value' => 'Asia/Bahrain', 'title' => '(UTC+03:00) Bahrain'],
            ['value' => 'Indian/Comoro', 'title' => '(UTC+03:00) Comoro'],
            ['value' => 'Africa/Dar_es_Salaam', 'title' => '(UTC+03:00) Dar es Salaam'],
            ['value' => 'Africa/Djibouti', 'title' => '(UTC+03:00) Djibouti'],
            ['value' => 'Africa/Juba', 'title' => '(UTC+03:00) Juba'],
            ['value' => 'Europe/Kaliningrad', 'title' => '(UTC+03:00) Kaliningrad'],
            ['value' => 'Africa/Kampala', 'title' => '(UTC+03:00) Kampala'],
            ['value' => 'Africa/Khartoum', 'title' => '(UTC+03:00) Khartoum'],
            ['value' => 'Asia/Kuwait', 'title' => '(UTC+03:00) Kuwait'],
            ['value' => 'Indian/Mayotte', 'title' => '(UTC+03:00) Mayotte'],
            ['value' => 'Europe/Minsk', 'title' => '(UTC+03:00) Minsk'],
            ['value' => 'Africa/Mogadishu', 'title' => '(UTC+03:00) Mogadishu'],
            ['value' => 'Africa/Nairobi', 'title' => '(UTC+03:00) Nairobi'],
            ['value' => 'Asia/Qatar', 'title' => '(UTC+03:00) Qatar'],
            ['value' => 'Asia/Riyadh', 'title' => '(UTC+03:00) Riyadh'],
            ['value' => 'Antarctica/Syowa', 'title' => '(UTC+03:00) Syowa'],
            ['value' => 'Asia/Tehran', 'title' => '(UTC+03:30) Tehran'],
            ['value' => 'Asia/Baku', 'title' => '(UTC+04:00) Baku'],
            ['value' => 'Asia/Dubai', 'title' => '(UTC+04:00) Dubai'],
            ['value' => 'Indian/Mahe', 'title' => '(UTC+04:00) Mahe'],
            ['value' => 'Indian/Mauritius', 'title' => '(UTC+04:00) Mauritius'],
            ['value' => 'Europe/Moscow', 'title' => '(UTC+04:00) Moscow'],
            ['value' => 'Asia/Muscat', 'title' => '(UTC+04:00) Muscat'],
            ['value' => 'Indian/Reunion', 'title' => '(UTC+04:00) Reunion'],
            ['value' => 'Europe/Samara', 'title' => '(UTC+04:00) Samara'],
            ['value' => 'Asia/Tbilisi', 'title' => '(UTC+04:00) Tbilisi'],
            ['value' => 'Europe/Volgograd', 'title' => '(UTC+04:00) Volgograd'],
            ['value' => 'Asia/Yerevan', 'title' => '(UTC+04:00) Yerevan'],
            ['value' => 'Asia/Kabul', 'title' => '(UTC+04:30) Kabul'],
            ['value' => 'Asia/Aqtau', 'title' => '(UTC+05:00) Aqtau'],
            ['value' => 'Asia/Aqtobe', 'title' => '(UTC+05:00) Aqtobe'],
            ['value' => 'Asia/Ashgabat', 'title' => '(UTC+05:00) Ashgabat'],
            ['value' => 'Asia/Dushanbe', 'title' => '(UTC+05:00) Dushanbe'],
            ['value' => 'Asia/Karachi', 'title' => '(UTC+05:00) Karachi'],
            ['value' => 'Indian/Kerguelen', 'title' => '(UTC+05:00) Kerguelen'],
            ['value' => 'Indian/Maldives', 'title' => '(UTC+05:00) Maldives'],
            ['value' => 'Antarctica/Mawson', 'title' => '(UTC+05:00) Mawson'],
            ['value' => 'Asia/Oral', 'title' => '(UTC+05:00) Oral'],
            ['value' => 'Asia/Samarkand', 'title' => '(UTC+05:00) Samarkand'],
            ['value' => 'Asia/Tashkent', 'title' => '(UTC+05:00) Tashkent'],
            ['value' => 'Asia/Colombo', 'title' => '(UTC+05:30) Colombo'],
            ['value' => 'Asia/Kolkata', 'title' => '(UTC+05:30) Kolkata'],
            ['value' => 'Asia/Kathmandu', 'title' => '(UTC+05:45) Kathmandu'],
            ['value' => 'Asia/Almaty', 'title' => '(UTC+06:00) Almaty'],
            ['value' => 'Asia/Bishkek', 'title' => '(UTC+06:00) Bishkek'],
            ['value' => 'Indian/Chagos', 'title' => '(UTC+06:00) Chagos'],
            ['value' => 'Asia/Dhaka', 'title' => '(UTC+06:00) Dhaka'],
            ['value' => 'Asia/Qyzylorda', 'title' => '(UTC+06:00) Qyzylorda'],
            ['value' => 'Asia/Thimphu', 'title' => '(UTC+06:00) Thimphu'],
            ['value' => 'Antarctica/Vostok', 'title' => '(UTC+06:00) Vostok'],
            ['value' => 'Asia/Yekaterinburg', 'title' => '(UTC+06:00) Yekaterinburg'],
            ['value' => 'Indian/Cocos', 'title' => '(UTC+06:30) Cocos'],
            ['value' => 'Asia/Rangoon', 'title' => '(UTC+06:30) Rangoon'],
            ['value' => 'Asia/Bangkok', 'title' => '(UTC+07:00) Bangkok'],
            ['value' => 'Indian/Christmas', 'title' => '(UTC+07:00) Christmas'],
            ['value' => 'Antarctica/Davis', 'title' => '(UTC+07:00) Davis'],
            ['value' => 'Asia/Ho_Chi_Minh', 'title' => '(UTC+07:00) Ho Chi Minh'],
            ['value' => 'Asia/Hovd', 'title' => '(UTC+07:00) Hovd'],
            ['value' => 'Asia/Jakarta', 'title' => '(UTC+07:00) Jakarta'],
            ['value' => 'Asia/Novokuznetsk', 'title' => '(UTC+07:00) Novokuznetsk'],
            ['value' => 'Asia/Novosibirsk', 'title' => '(UTC+07:00) Novosibirsk'],
            ['value' => 'Asia/Omsk', 'title' => '(UTC+07:00) Omsk'],
            ['value' => 'Asia/Phnom_Penh', 'title' => '(UTC+07:00) Phnom Penh'],
            ['value' => 'Asia/Pontianak', 'title' => '(UTC+07:00) Pontianak'],
            ['value' => 'Asia/Vientiane', 'title' => '(UTC+07:00) Vientiane'],
            ['value' => 'Asia/Brunei', 'title' => '(UTC+08:00) Brunei'],
            ['value' => 'Antarctica/Casey', 'title' => '(UTC+08:00) Casey'],
            ['value' => 'Asia/Choibalsan', 'title' => '(UTC+08:00) Choibalsan'],
            ['value' => 'Asia/Chongqing', 'title' => '(UTC+08:00) Chongqing'],
            ['value' => 'Asia/Harbin', 'title' => '(UTC+08:00) Harbin'],
            ['value' => 'Asia/Hong_Kong', 'title' => '(UTC+08:00) Hong Kong'],
            ['value' => 'Asia/Kashgar', 'title' => '(UTC+08:00) Kashgar'],
            ['value' => 'Asia/Krasnoyarsk', 'title' => '(UTC+08:00) Krasnoyarsk'],
            ['value' => 'Asia/Kuala_Lumpur', 'title' => '(UTC+08:00) Kuala Lumpur'],
            ['value' => 'Asia/Kuching', 'title' => '(UTC+08:00) Kuching'],
            ['value' => 'Asia/Macau', 'title' => '(UTC+08:00) Macau'],
            ['value' => 'Asia/Makassar', 'title' => '(UTC+08:00) Makassar'],
            ['value' => 'Asia/Manila', 'title' => '(UTC+08:00) Manila'],
            ['value' => 'Australia/Perth', 'title' => '(UTC+08:00) Perth'],
            ['value' => 'Asia/Shanghai', 'title' => '(UTC+08:00) Shanghai'],
            ['value' => 'Asia/Singapore', 'title' => '(UTC+08:00) Singapore'],
            ['value' => 'Asia/Taipei', 'title' => '(UTC+08:00) Taipei'],
            ['value' => 'Asia/Ulaanbaatar', 'title' => '(UTC+08:00) Ulaanbaatar'],
            ['value' => 'Asia/Urumqi', 'title' => '(UTC+08:00) Urumqi'],
            ['value' => 'Australia/Eucla', 'title' => '(UTC+08:45) Eucla'],
            ['value' => 'Asia/Dili', 'title' => '(UTC+09:00) Dili'],
            ['value' => 'Asia/Irkutsk', 'title' => '(UTC+09:00) Irkutsk'],
            ['value' => 'Asia/Jayapura', 'title' => '(UTC+09:00) Jayapura'],
            ['value' => 'Pacific/Palau', 'title' => '(UTC+09:00) Palau'],
            ['value' => 'Asia/Pyongyang', 'title' => '(UTC+09:00) Pyongyang'],
            ['value' => 'Asia/Seoul', 'title' => '(UTC+09:00) Seoul'],
            ['value' => 'Asia/Tokyo', 'title' => '(UTC+09:00) Tokyo'],
            ['value' => 'Australia/Adelaide', 'title' => '(UTC+09:30) Adelaide'],
            ['value' => 'Australia/Broken_Hill', 'title' => '(UTC+09:30) Broken Hill'],
            ['value' => 'Australia/Darwin', 'title' => '(UTC+09:30) Darwin'],
            ['value' => 'Australia/Brisbane', 'title' => '(UTC+10:00) Brisbane'],
            ['value' => 'Pacific/Chuuk', 'title' => '(UTC+10:00) Chuuk'],
            ['value' => 'Australia/Currie', 'title' => '(UTC+10:00) Currie'],
            ['value' => 'Antarctica/DumontDUrville', 'title' => '(UTC+10:00) DumontDUrville'],
            ['value' => 'Pacific/Guam', 'title' => '(UTC+10:00) Guam'],
            ['value' => 'Australia/Hobart', 'title' => '(UTC+10:00) Hobart'],
            ['value' => 'Asia/Khandyga', 'title' => '(UTC+10:00) Khandyga'],
            ['value' => 'Australia/Lindeman', 'title' => '(UTC+10:00) Lindeman'],
            ['value' => 'Australia/Melbourne', 'title' => '(UTC+10:00) Melbourne'],
            ['value' => 'Pacific/Port_Moresby', 'title' => '(UTC+10:00) Port Moresby'],
            ['value' => 'Pacific/Saipan', 'title' => '(UTC+10:00) Saipan'],
            ['value' => 'Australia/Sydney', 'title' => '(UTC+10:00) Sydney'],
            ['value' => 'Asia/Yakutsk', 'title' => '(UTC+10:00) Yakutsk'],
            ['value' => 'Australia/Lord_Howe', 'title' => '(UTC+10:30) Lord Howe'],
            ['value' => 'Pacific/Efate', 'title' => '(UTC+11:00) Efate'],
            ['value' => 'Pacific/Guadalcanal', 'title' => '(UTC+11:00) Guadalcanal'],
            ['value' => 'Pacific/Kosrae', 'title' => '(UTC+11:00) Kosrae'],
            ['value' => 'Antarctica/Macquarie', 'title' => '(UTC+11:00) Macquarie'],
            ['value' => 'Pacific/Noumea', 'title' => '(UTC+11:00) Noumea'],
            ['value' => 'Pacific/Pohnpei', 'title' => '(UTC+11:00) Pohnpei'],
            ['value' => 'Asia/Sakhalin', 'title' => '(UTC+11:00) Sakhalin'],
            ['value' => 'Asia/Ust-Nera', 'title' => '(UTC+11:00) Ust-Nera'],
            ['value' => 'Asia/Vladivostok', 'title' => '(UTC+11:00) Vladivostok'],
            ['value' => 'Pacific/Norfolk', 'title' => '(UTC+11:30) Norfolk'],
            ['value' => 'Asia/Anadyr', 'title' => '(UTC+12:00) Anadyr'],
            ['value' => 'Pacific/Auckland', 'title' => '(UTC+12:00) Auckland'],
            ['value' => 'Pacific/Fiji', 'title' => '(UTC+12:00) Fiji'],
            ['value' => 'Pacific/Funafuti', 'title' => '(UTC+12:00) Funafuti'],
            ['value' => 'Asia/Kamchatka', 'title' => '(UTC+12:00) Kamchatka'],
            ['value' => 'Pacific/Kwajalein', 'title' => '(UTC+12:00) Kwajalein'],
            ['value' => 'Asia/Magadan', 'title' => '(UTC+12:00) Magadan'],
            ['value' => 'Pacific/Majuro', 'title' => '(UTC+12:00) Majuro'],
            ['value' => 'Antarctica/McMurdo', 'title' => '(UTC+12:00) McMurdo'],
            ['value' => 'Pacific/Nauru', 'title' => '(UTC+12:00) Nauru'],
            ['value' => 'Antarctica/South_Pole', 'title' => '(UTC+12:00) South Pole'],
            ['value' => 'Pacific/Tarawa', 'title' => '(UTC+12:00) Tarawa'],
            ['value' => 'Pacific/Wake', 'title' => '(UTC+12:00) Wake'],
            ['value' => 'Pacific/Wallis', 'title' => '(UTC+12:00) Wallis'],
            ['value' => 'Pacific/Chatham', 'title' => '(UTC+12:45) Chatham'],
            ['value' => 'Pacific/Apia', 'title' => '(UTC+13:00) Apia'],
            ['value' => 'Pacific/Enderbury', 'title' => '(UTC+13:00) Enderbury'],
            ['value' => 'Pacific/Fakaofo', 'title' => '(UTC+13:00) Fakaofo'],
            ['value' => 'Pacific/Tongatapu', 'title' => '(UTC+13:00) Tongatapu'],
            ['value' => 'Pacific/Kiritimati', 'title' => '(UTC+14:00) Kiritimati'],
        ];
    }
}
